// Bundles view/ into one self-contained HTML string and writes it as a TS module,
// so the server ships the card inside its own JS with no file lookups at runtime.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import * as esbuild from "esbuild";

const root = join(import.meta.dirname, "..");

export const buildCardHtml = async () => {
  const [html, css] = await Promise.all([
    readFile(join(root, "view/card.html"), "utf8"),
    readFile(join(root, "view/card.css"), "utf8"),
  ]);
  const bundle = await esbuild.build({
    entryPoints: [join(root, "view/app.ts")],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    minify: true,
    write: false,
    legalComments: "none",
  });
  const script = bundle.outputFiles[0].text.replace(/<\/(script|style)/gi, "<\\/$1");
  return html
    .replace("</head>", () => `<style>${css}</style></head>`)
    .replace("</body>", () => `<script>${script}</script></body>`);
};

if (import.meta.filename === process.argv[1]) {
  const page = await buildCardHtml();
  await mkdir(join(root, "src/generated"), { recursive: true });
  await writeFile(join(root, "src/generated/card.ts"), `// Generated by scripts/build-view.mjs. Do not edit.\nexport const CARD_HTML: string = ${JSON.stringify(page)};\n`);
  console.log(`card: ${page.length} bytes`);
}
